// Generated by CoffeeScript 1.9.2
(function() {
  var config, count, documentDBUtils, filterQuery, processResponse;

  documentDBUtils = require('./documentDBUtils').documentDBUtils;

  filterQuery = null;

  count = require('./count').count;

  config = {
    databaseID: 'test-stored-procedure',
    collectionID: 'test-stored-procedure',
    storedProcedureID: 'count',
    storedProcedureJS: count,
    memo: {
      filterQuery: filterQuery
    },
    debug: false
  };

  processResponse = function(err, response) {
    if (err != null) {
      console.dir(err);
      throw new Error(err);
    }
    console.log(response.stats);
    return console.log(response.memo);
  };

  documentDBUtils(config, processResponse);

}).call(this);
