// Generated by CoffeeScript 1.9.2
(function() {
  var count;

  count = function(memo) {
    var collection, executionStartTime, maxExecutionTime, maxRowCountPerExececution, onReadDocuments, query, rowCountForThisExecution, setBody;
    collection = getContext().getCollection();
    maxRowCountPerExececution = 100000;
    rowCountForThisExecution = 0;
    maxExecutionTime = 5000 * 0.9;
    executionStartTime = new Date().getTime();
    if (memo == null) {
      memo = {};
    }
    if (memo.count == null) {
      memo.count = 0;
    }
    if (memo.continuation == null) {
      memo.continuation = null;
    }
    memo.stillTime = true;
    memo.stillResources = true;
    memo.underMaxRowCount = true;
    query = function(responseOptions) {
      memo.stillTime = (new Date().getTime() - executionStartTime) < maxExecutionTime;
      memo.underMaxRowCount = rowCountForThisExecution < maxRowCountPerExececution;
      if (memo.underMaxRowCount && memo.stillTime && memo.stillResources) {
        responseOptions = {
          continuation: memo.continuation,
          pageSize: 1000
        };
        if (memo.filterQuery != null) {
          memo.stillResources = collection.queryDocuments(collection.getSelfLink(), memo.filterQuery, responseOptions, onReadDocuments);
        } else {
          memo.stillResources = collection.readDocuments(collection.getSelfLink(), responseOptions, onReadDocuments);
        }
      }
      return setBody();
    };
    onReadDocuments = function(err, docFeed, responseOptions) {
      if (err) {
        throw err;
      }
      count = docFeed.length;
      memo.count += count;
      rowCountForThisExecution += count;
      if (responseOptions.continuation != null) {
        memo.continuation = responseOptions.continuation;
        return query();
      } else {
        memo.continuation = null;
        return setBody();
      }
    };
    setBody = function() {
      return getContext().getResponse().setBody(memo);
    };
    return query();
  };

  exports.count = count;

}).call(this);
