// Generated by CoffeeScript 1.9.2
(function() {
  var config, documentDBUtils, hello, processResponse;

  documentDBUtils = require('./');

  hello = require('./hello').hello;

  config = {
    databaseID: 'test-stored-procedure',
    collectionID: 'test-stored-procedure',
    storedProcedureID: 'hello',
    storedProcedureJS: hello,
    memo: {}
  };

  processResponse = function(err, response) {
    var config2;
    if (err != null) {
      throw err;
    }
    console.log('First execution including sending stored procedure to DocumentDB');
    console.log(response.memo);
    console.log(response.stats);
    console.log('storedProcedure');
    console.dir(response.storedProcedure);
    config2 = {
      storedProcedureLink: response.storedProcedureLink,
      memo: {}
    };
    return documentDBUtils(config2, function(err, response) {
      if (err) {
        throw err;
      }
      console.log('\nSecond execution');
      console.log(response.memo);
      return console.log(response.stats);
    });
  };

  documentDBUtils(config, processResponse);

}).call(this);
